import argparse
import json
import os
import re
import openai
from dotenv import load_dotenv
from openai import OpenAI
from datetime import datetime

import google.generativeai as genai

load_dotenv()
openai.api_key = os.getenv("OPENAI_API_KEY")
summary_path_1 = "summaries/summary_gpt-4o_What's_a_good_momentum_strategy_for_TSLA_over_the_past_3_months?_20250420_151153.json"
with open(summary_path_1, "r") as f:
        summary_1 = json.load(f)

print(summary_1)
question = "What's a good momentum strategy for TSLA over the past 3 months?"
# Final prompt
system_prompt = "You are a financial strategy analyst. Judge and improve strategy, code, and results generated by LLM agent."
user_prompt = f"""
Judge strategy below for the following finance question:
**{question}**

Instructions:
- Evaluate clarity and reasoning of the steps
- Evaluate usefulness and correctness of the code
- Explain the stretegy strategy
- Provide a one-paragraph natural language summary as final judgment

{summary_1}


"""

print("\n[INFO] Asking GPT-4o to compare strategies...")

    # Send to GPT-4o
response = openai.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ],
        temperature=0.7
)

content = response.choices[0].message.content.strip()
print("\n===== 🧠 Comparison Result =====")
print(content)